/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // Agentic-inspired palette — values from CSS vars (see index.css themes).
        oct: {
          bg: 'var(--oct-bg)',
          panel: 'var(--oct-panel)',
          surface: 'var(--oct-surface)',
          'surface-raised': 'var(--oct-surface-raised)',
          border: 'var(--oct-border)',
          'border-bright': 'var(--oct-border-bright)',
          text: 'var(--oct-text)',
          muted: 'var(--oct-muted)',
          accent: 'var(--oct-accent)',
          'accent-hover': 'var(--oct-accent-hover)',
          flame: 'var(--oct-flame)',
          'accent-dim': 'var(--oct-accent-dim)',
          live: 'var(--oct-live)',
          'live-dim': 'var(--oct-live-dim)',
          green: 'var(--oct-green)',
          yellow: 'var(--oct-yellow)',
        },
        discord: {
          dark: 'var(--oct-bg)',
          darker: 'var(--oct-surface)',
          sidebar: 'var(--oct-surface)',
          main: 'var(--oct-surface-raised)',
          input: 'var(--oct-surface-raised)',
          hover: 'var(--oct-surface-raised)',
          'hover-light': 'var(--oct-border)',
          border: 'var(--oct-border)',
          blurple: 'var(--oct-accent)',
          'blurple-hover': 'var(--oct-accent-hover)',
          green: 'var(--oct-green)',
          red: 'var(--oct-flame)',
          yellow: 'var(--oct-yellow)',
          text: 'var(--oct-text)',
          'text-normal': 'var(--oct-text)',
          'text-muted': 'var(--oct-muted)',
          'text-link': 'var(--oct-accent)',
          'header-primary': 'var(--oct-text)',
          'header-secondary': 'var(--oct-muted)',
          'channel-icon': 'var(--oct-muted)',
          divider: 'var(--oct-border)',
          'embed-bg': 'var(--oct-surface)',
          highlight: 'var(--oct-accent-dim)',
          'mention-bg': 'var(--oct-accent-dim)',
          'scrollbar-thin-track': 'var(--oct-bg)',
          'scrollbar-thin-thumb': 'var(--oct-border)',
        },
      },
      fontFamily: {
        display: ['Fraunces', 'Georgia', 'serif'],
        sans: ['"Space Grotesk"', 'system-ui', 'sans-serif'],
        mono: ['"JetBrains Mono"', 'ui-monospace', 'monospace'],
        discord: ['"Space Grotesk"', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        cockpit: '0px',
      },
      borderWidth: {
        3: '3px',
      },
      boxShadow: {
        'oct-glow': '4px 4px 0 0 var(--oct-shadow)',
        'oct-hard': '4px 4px 0 0 var(--oct-shadow)',
        'oct-hard-sm': '2px 2px 0 0 var(--oct-shadow)',
        'oct-hard-lg': '6px 6px 0 0 var(--oct-shadow)',
        'oct-hard-red': '4px 4px 0 0 var(--oct-accent)',
        'oct-hard-red-sm': '2px 2px 0 0 var(--oct-accent)',
      },
      keyframes: {
        'pulse-live': {
          '0%, 100%': { opacity: '1', boxShadow: '0 0 0 0 var(--oct-live-pulse)' },
          '50%': { opacity: '0.7', boxShadow: '0 0 0 3px transparent' },
        },
        'pulse-pending': {
          '0%, 100%': { opacity: '1', boxShadow: '0 0 0 0 rgba(251, 191, 36, 0.5)' },
          '50%': { opacity: '0.7', boxShadow: '0 0 0 3px rgba(251, 191, 36, 0)' },
        },
      },
      animation: {
        'pulse-live': 'pulse-live 2.4s ease-in-out infinite',
        'pulse-pending': 'pulse-pending 2.8s ease-in-out infinite',
      },
    },
  },
  plugins: [],
};
