// Canonical shared types now live in @oct/shared. This module re-exports them so
// existing `../discord/types.js` importers across the backend keep working
// unchanged. Values (GatewayOpcodes, PUSHOVER_SOUNDS) are re-exported as values;
// everything else is type-only.
export { GatewayOpcodes } from '@oct/shared';

export type {
  DiscordUser,
  DiscordGuild,
  DiscordChannel,
  DiscordReaction,
  DiscordMessage,
  DiscordAttachment,
  DiscordEmbed,
  GatewayPayload,
  MessageSource,
  ChannelRef,
  HighlightMode,
  MessageDisplay,
  SplitLayout,
  KeywordMatchMode,
  KeywordPattern,
  Room,
  PushoverPriority,
  PushoverSound,
  PushoverTriggers,
  MissedRunnerConfig,
  MissedRunnerNotifyVia,
  ToastPosition,
  PushoverFilters,
  PushoverConfig,
  SolPlatform,
  EvmPlatform,
  ContractClickAction,
  BadgeClickAction,
  ContractLinkTemplates,
  SoundType,
  SoundConfig,
  SoundSettings,
  AppConfig,
  TelegramChatInfo,
  GuildInfo,
  DMChannel,
  FrontendReaction,
  TelegramSticker,
  TelegramPoll,
  TelegramForward,
  TelegramButton,
  FrontendMessage,
} from '@oct/shared';
